name: drupal-boilerplate
recipe: drupal10

config:
  php: "8.2"
  composer_version: "2"
  webroot: web

proxy:
  node:
    # Change drupal-boilerplate to match "name:" when renaming project.
    - "node-drupal-boilerplate.lndo.site:3000"

services:
  appserver:
    api: 3
    healthcheck: drush sql:query ';'
    overrides:
      environment:
        ENVIRONMENT_TYPE: development
        DRUSH_OPTIONS_URI: "https://drupal-boilerplate.lndo.site"
    build:
      - composer install --profile

  database:
    api: 3
    type: mariadb:custom
    overrides:
      image: bitnami/mariadb:10.11-debian-11

  memcached:
    api: 3
    type: memcached:custom
    mem: 64
    overrides:
      image: bitnami/memcached:1-debian-11
      environment:
        MEMCACHED_MAX_ITEM_SIZE: 8388608

  mailhog:
    api: 3
    type: mailhog
    overrides:
      platform: linux/amd64
    hogfrom:
      - appserver

  node:
    api: 3
    type: node:18
    ssl: true
    sslExpose: false
    port: 3000
    scanner: false

tooling:
  npm:
    service: node
    description: Run NPM commands within the node service.

  theme:
    service: node
    description: Run NPM commands for the theme.
    dir: /app/web/themes/contrib/dvb
    cmd: npm

events:
  post-start:
    - appserver: >
        if ! drush status --field=bootstrap | grep -qi "successful"; then
          drush si --existing-config --account-name=admin -y;
        fi
