name: drupal-boilerplate
recipe: drupal10

config:
  php: '8.1'
  composer_version: '2.6.4'
  webroot: web
  build:
    - composer install --profile

proxy:
  node:
    # Change drupal-boilerplate to match "name:" when renaming project.
    - "node.drupal-boilerplate.lndo.site:3000"

services:
  appserver:
    healthcheck: drush sql:query ';'
    overrides:
      environment:
        ENVIRONMENT_TYPE: development
        DRUSH_OPTIONS_URI: "https://drupal-boilerplate.lndo.site"

  database:
    type: mariadb:custom
    overrides:
      image: bitnami/mariadb:10.11-debian-11

  memcached:
    type: memcached:custom
    mem: 64
    overrides:
      image: bitnami/memcached:1-debian-11
      environment:
        MEMCACHED_MAX_ITEM_SIZE: 8388608

  mailhog:
    type: mailhog:custom
    overrides:
      image: anatomicjc/mailhog:1.0.1
    hogfrom:
      - appserver

  node:
    type: node:18
    ssl: true
    sslExpose: false
    port: 3000
    scanner: false

tooling:
  npm:
    service: node
    description: Run NPM commands within the node service.

  theme:
    service: node
    description: Run NPM commands for the theme.
    dir: /app/web/themes/contrib/dvb
    cmd: npm

events:
  post-start:
    - appserver: >
        if ! drush status --field=bootstrap | grep -qi "successful"; then
          drush si --existing-config --account-name=admin -y;
        fi
