
x-volumes:
  &default-volumes
  volumes:
    - ./private:/app/private:delegated
    - ./web/sites/default/files:/app/web/sites/default/files:delegated

services:
  cli:
    image: &cli-image ${COMPOSE_PROJECT_NAME:-drupal}-cli
    build:
      context: .
      dockerfile: .docker/cli.dockerfile
    <<: *default-volumes
    env_file:
      - .env

  php:
    build:
      context: .
      dockerfile: .docker/php.dockerfile
      args:
        CLI_IMAGE: *cli-image
    <<: *default-volumes
    depends_on:
      - cli
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
      args:
        CLI_IMAGE: *cli-image
    <<: *default-volumes
    depends_on:
      - cli
      - php
