
x-volumes:
  &default-volumes
  volumes:
    - ./private:/app/private:delegated
    - ./web/sites/default/files:/app/web/sites/default/files:delegated

services:
  database:
    image: mariadb:11.0
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'true'
      MARIADB_DATABASE: ${MARIADB_DATABASE:-drupal10}
      MARIADB_USER: ${MARIADB_USER:-drupal10}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-drupal10}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 2s
      retries: 120

  memcached:
    image: memcached:1.6-alpine
    environment:
      MEMCACHED_MAX_ITEM_SIZE: 8388608

  php:
    image: &php-image ${COMPOSE_PROJECT_NAME:-drupal}-php
    build:
      context: .
      dockerfile: .docker/php.dockerfile
    <<: *default-volumes
    depends_on:
      database:
        condition: service_healthy
      memcached:
        condition: service_started

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
      args:
        PHP_IMAGE: *php-image
    <<: *default-volumes
    depends_on:
      - php

volumes:
  mariadb:
