version: '3.6'

services:
  memcached:
    container_name: ddev-${DDEV_SITENAME}-memcached
    image: memcached:1.6
    restart: "no"
    expose:
      - 11211
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    # Arguments passed to the memcached binary.
    command: ["-m", "64"]

    environment:
      MEMCACHED_MAX_ITEM_SIZE: 8388608

    volumes:
      - ".:/mnt/ddev_config"
