name: Build

on:
  push:
    branches: [main]

env:
  TERM: xterm

jobs:
  lando:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lando install
        run: |
          sudo curl -fsSL -o /usr/local/bin/lando "https://github.com/lando/cli/releases/download/v3.20.4/lando-linux-x64-v3.20.4"
          sudo chmod +x /usr/local/bin/lando

      - uses: actions/cache@v3
        with:
          path: ~/.lando/cache
          key: lando-3.20.4-${{ github.ref }}
          restore-keys: |
            lando-3.20.4-

      - name: Lando start
        run: lando start
