name: Build

on:
  push:
    branches: [main]

jobs:
  lando:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lando/setup-lando@v2

  ddev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ddev/github-action-setup-ddev@v1
