name: Docker Compose

on:
  release:
    types: [created]
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create env
        run: cp .env.example .env

      - name: Start containers
        run: docker-compose up -d --build

      - name: Install Drupal
        run: docker-compose exec -it cli drush si --existing-config --account-name=admin -y

      - name: Stop containers
        if: always()
        run: docker-compose down --rmi all -v --remove-orphans
